# Generated by Django 5.2.1 on 2025-07-16 14:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='Unique URL-friendly identifier for this exercise.', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='exercisecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='Unique URL-friendly identifier for this category.', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='trainingday',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='Unique URL-friendly identifier for this exercise.', populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='Unique URL-friendly identifier for this exercise.', populate_from='name', unique=True),
        ),
    ]
