# Generated by Django 5.2.1 on 2025-07-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_exercise_slug_alter_exercisecategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingday',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Provide a description for this training day.'),
        ),
    ]
