# Generated by Django 5.2.1 on 2025-07-21 14:16

import autoslug.fields
import workouts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_trainingday_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingday',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='Unique URL-friendly identifier for this exercise.', populate_from=workouts.models.TrainingDay.get_slug, unique=True),
        ),
    ]
