# Generated by Django 5.2.1 on 2025-07-22 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_trainingday_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexercise',
            name='owner',
            field=models.ForeignKey(default=uuid.UUID('b43120d9-cf1a-4f43-9c2e-ecec5dbecfdf'), on_delete=django.db.models.deletion.CASCADE, related_name='daily_exercises', related_query_name='daily_exercise', to=settings.AUTH_USER_MODEL),
        ),
    ]
