# Generated by Django 5.2.1 on 2025-07-22 20:08

import django.db.models.deletion
import workouts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_dailyexercise_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexercise',
            name='owner',
            field=models.ForeignKey(default=workouts.models.get_admin_pk, on_delete=django.db.models.deletion.CASCADE, related_name='daily_exercises', related_query_name='daily_exercise', to=settings.AUTH_USER_MODEL),
        ),
    ]
