# Generated by Django 5.2.1 on 2025-07-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_dailyexercise_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyexercise',
            old_name='repetitions',
            new_name='repeats',
        ),
    ]
