# Generated by Django 5.2.1 on 2025-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_rename_repetitions_dailyexercise_repeats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexercise',
            name='actual_used_weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Actual weight used during the exercise.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dailyexercise',
            name='repeats',
            field=models.PositiveSmallIntegerField(help_text='Number of repeats for this exercise.'),
        ),
        migrations.AlterField(
            model_name='dailyexercise',
            name='work_weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Planned weight to be used for this exercise.', max_length=3, null=True),
        ),
    ]
