# Generated by Django 5.2.1 on 2025-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_dailyexercise_actual_used_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexercise',
            name='actual_used_weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Actual weight used during the exercise.', null=True),
        ),
        migrations.AlterField(
            model_name='dailyexercise',
            name='work_weight',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Planned weight to be used for this exercise.', null=True),
        ),
    ]
