# Generated by Django 5.2.1 on 2025-07-23 16:13

import autoslug.fields
import workouts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_dailyexercise_actual_used_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexercise',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default-slug', editable=False, help_text='Unique URL-friendly identifier for this exercise.', populate_from=workouts.models.DailyExercise.get_slug, unique=True),
            preserve_default=False,
        ),
    ]
