# Generated by Django 5.2.1 on 2025-08-05 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_dailyexercise_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='unique_for_category',
        ),
        migrations.AddConstraint(
            model_name='dailyexercise',
            constraint=models.UniqueConstraint(fields=('day', 'order'), name='unique_for_day'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('name', 'exercise_category', 'owner'), name='unique_for_user'),
        ),
        migrations.AddConstraint(
            model_name='exercisecategory',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name_for_owner'),
        ),
    ]
